room1 = Room.create(description:"This is the first room")
room2 = Room.create(description:"This is the second room")
room3 = Room.create(description:"This is the third room")
# user1 = User.create(name: "Greg")
backpack = Item.create(name: "backpack")
flashlight = Item.create(name: "flashlight")
candy_bar = Item.create(name: "candy bar")
